development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7a5fcb29e21069fdb5024d53c90e25a3@sole.redistogo.com:10004/
  channel_prefix: chat_app_production
