development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:cc7d4f9346fe35a6b9f89253609cace8@sole.redistogo.com:10004/
  channel_prefix: chat_app_production
